# Generated by Django 3.1.1 on 2020-10-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20200928_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=40)),
                ('verify_email', models.EmailField(max_length=40)),
                ('text', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Register',
            },
        ),
    ]
