# Generated by Django 3.1.1 on 2020-10-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registration',
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name_plural': 'Registration'},
        ),
    ]
